"""empty message

Revision ID: 364f6e280a2e
Revises: 
Create Date: 2024-09-28 12:34:35.412458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '364f6e280a2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('OrgID', sa.Integer(), nullable=False),
    sa.Column('OrgName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('OrgID'),
    sa.UniqueConstraint('OrgName')
    )
    op.create_table('projects',
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('ProjectName', sa.String(length=100), nullable=False),
    sa.Column('OrgID', sa.Integer(), nullable=False),
    sa.Column('RequiredResources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('NumberOfDays', sa.Integer(), nullable=False),
    sa.Column('ProjectStartDate', sa.Date(), nullable=False),
    sa.Column('Technology', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('Domain', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['OrgID'], ['organizations.OrgID'], ),
    sa.PrimaryKeyConstraint('ProjectID'),
    sa.UniqueConstraint('ProjectName')
    )
    op.create_table('teams',
    sa.Column('TeamID', sa.Integer(), nullable=False),
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('TotalResources', sa.Integer(), nullable=False),
    sa.Column('OrgID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['OrgID'], ['organizations.OrgID'], ),
    sa.ForeignKeyConstraint(['ProjectID'], ['projects.ProjectID'], ),
    sa.PrimaryKeyConstraint('TeamID'),
    sa.UniqueConstraint('ProjectID')
    )
    op.create_table('resources',
    sa.Column('ResourceID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('PastJobTitles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('Domain', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('AvailableDate', sa.Date(), nullable=True),
    sa.Column('OrgID', sa.Integer(), nullable=False),
    sa.Column('TeamID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrgID'], ['organizations.OrgID'], ),
    sa.ForeignKeyConstraint(['TeamID'], ['teams.TeamID'], ),
    sa.PrimaryKeyConstraint('ResourceID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    op.drop_table('teams')
    op.drop_table('projects')
    op.drop_table('organizations')
    # ### end Alembic commands ###
