"""empty message

Revision ID: 6fdb3a10b497
Revises: 
Create Date: 2024-09-27 01:08:14.602702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdb3a10b497'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('OrgID', sa.Integer(), nullable=False),
    sa.Column('OrgName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('OrgID')
    )
    op.create_table('projects',
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('ProjectName', sa.String(length=200), nullable=False),
    sa.Column('NumberOfDays', sa.Integer(), nullable=True),
    sa.Column('ProjectStartDate', sa.Date(), nullable=True),
    sa.Column('Technology', sa.String(length=200), nullable=True),
    sa.Column('Domain', sa.String(length=100), nullable=True),
    sa.Column('RequiredResources', sa.JSON(), nullable=True),
    sa.Column('OrgID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrgID'], ['organizations.OrgID'], ),
    sa.PrimaryKeyConstraint('ProjectID')
    )
    op.create_table('resources',
    sa.Column('ResourceID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Skills', sa.JSON(), nullable=True),
    sa.Column('PastJobTitles', sa.JSON(), nullable=True),
    sa.Column('Domain', sa.JSON(), nullable=True),
    sa.Column('AvailableDate', sa.Date(), nullable=True),
    sa.Column('OrgID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrgID'], ['organizations.OrgID'], ),
    sa.PrimaryKeyConstraint('ResourceID')
    )
    op.create_table('teams',
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('ResourceIDs', sa.JSON(), nullable=True),
    sa.Column('TotalResources', sa.Integer(), nullable=True),
    sa.Column('OrgID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrgID'], ['organizations.OrgID'], ),
    sa.ForeignKeyConstraint(['ProjectID'], ['projects.ProjectID'], ),
    sa.PrimaryKeyConstraint('ProjectID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('resources')
    op.drop_table('projects')
    op.drop_table('organizations')
    # ### end Alembic commands ###
